"""Original NEON WARDEN six-voice score. No sampled/licensed music.

32 eighth-note steps per phrase, four harmonic variations per full loop.
0 = rest; 255 = tie. MIDI pitches 24..95. SID clock follows PAL/NTSC.
"""
from pathlib import Path
import json
P = Path(__file__).resolve().parent
titles = ['Sump Circuit', 'Undertow', 'Names in Glass', 'Above the Grid',
          'Photosynthetic Static', 'Warden Protocol']
roots = [33, 38, 36, 40, 35, 30]
chords = [[0, 3, -4, -2], [0, -5, 3, -2], [0, 5, 3, -2],
          [0, -2, 3, 5], [0, 3, 7, 5], [0, 1, 0, -2]]
motifs = [[12, 0, 19, 15, 0, 14, 10, 0],
          [0, 12, 0, 7, 0, 10, 0, 14],
          [12, 19, 22, 19, 15, 22, 24, 19],
          [12, 12, 19, 0, 22, 19, 15, 14],
          [19, 0, 0, 15, 0, 14, 0, 12],
          [12, 13, 0, 12, 7, 0, 6, 7]]
tempos = [5, 6, 5, 4, 6, 4]
out = ['; Generated by music.py; six interleaved voices per step.']
def emit(name, data):
    out.append(name + ': .byte ' + ','.join(map(str, data)))
manifest = []
for song in range(6):
    data = []
    for bar in range(4):
        root = roots[song] + chords[song][bar]
        for beat in range(8):
            bass = root + (7 if beat == 6 else 12 if beat == 7 else 0)
            if song in (1, 4) and beat in (1, 3, 5): bass = 0
            lead = motifs[song][(beat + (2 if bar == 3 else 0)) % 8]
            lead = root + 12 + lead if lead else 0
            drum = 48 if beat in (2, 6) else 84 if beat % 2 else 0
            pad = root + 24 if beat == 0 else 255
            arp = root + 24 + [0, 7, 3, 12, 7, 15, 12, 7][beat]
            if song in (1, 4) and beat % 2 == 0: arp = 0
            counter = root + 19 if beat in (0, 4) else 255 if beat in (1, 5) else 0
            if song == 5: counter = root + 12 if beat % 2 == 0 else 0
            data += [bass, lead, drum, pad, arp, counter]
    emit('song'+str(song), data)
    manifest.append(dict(district=song+1, title=titles[song], bpm=750/tempos[song],
                         loop_seconds=128*tempos[song]/25, voices=6, steps=data))
for suffix,op in [('lo','<'),('hi','>')]:
    out.append('song'+suffix+': .byte '+','.join(op+'song'+str(i) for i in [0,1,2,3,4,5,3]))
emit('songtempo', tempos+[tempos[3]])
emit('songshift', [0, 0, 5, 0])
for clock,suffix in [(985248,'pal'),(1022727,'ntsc')]:
    f = [round(440*2**((n-69)/12)*16777216/clock) for n in range(24,96)]
    emit('freqlo_'+suffix,[v&255 for v in f])
    emit('freqhi_'+suffix,[v>>8 for v in f])
(P/'music.inc').write_text('\n'.join(out)+'\n')
(P/'music.json').write_text(json.dumps(manifest,indent=2)+'\n')
